#!/usr/bin/env bash
# Idempotent, self-healing bootstrap. Re-run any time; converges to a working state.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${REPO_ROOT}"

step()  { printf "\033[1;34m[bootstrap]\033[0m %s\n" "$*"; }
ok()    { printf "  \033[1;32m[ok]\033[0m %s\n" "$*"; }
fix()   { printf "  \033[1;33m[fix]\033[0m %s\n" "$*"; }
skip()  { printf "  \033[1;36m[skip]\033[0m %s\n" "$*"; }
fail()  { printf "  \033[1;31m[fail]\033[0m %s\n" "$*"; exit 1; }
warn()  { printf "  \033[1;33m[warn]\033[0m %s\n" "$*"; }

# ----- 1) uv -----
step "checking uv"
if ! command -v uv >/dev/null 2>&1; then
  fix "uv not found; installing to ~/.local/bin"
  if command -v curl >/dev/null 2>&1; then
    curl -LsSf https://astral.sh/uv/install.sh | sh
  elif command -v wget >/dev/null 2>&1; then
    wget -qO- https://astral.sh/uv/install.sh | sh
  else
    fail "need curl or wget to install uv"
  fi
  export PATH="${HOME}/.local/bin:${PATH}"
  command -v uv >/dev/null 2>&1 || fail "uv install failed; add ~/.local/bin to PATH"
fi
ok "uv $(uv --version | awk '{print $2}')"

# ----- 2) venv + sync -----
step "syncing .venv via uv"
if [[ ! -d .venv ]]; then
  fix "creating .venv"
fi
# autoheal: retry sync once after clearing cache on transient failures
if ! uv sync --all-packages 2>/tmp/uv-sync.log; then
  warn "uv sync failed; attempting autoheal (cache clean + retry)"
  uv cache clean || true
  if ! uv sync --all-packages; then
    warn "retrying with llama-cpp-python native build disabled"
    CMAKE_ARGS="-DLLAMA_NATIVE=OFF" FORCE_CMAKE=1 uv sync --all-packages \
      || fail "uv sync failed; see /tmp/uv-sync.log"
  fi
fi
ok ".venv populated"

# ----- 3) prerequisites -----
step "probing toolchain"
if command -v cc >/dev/null 2>&1 || command -v gcc >/dev/null 2>&1; then
  ok "C compiler present"
else
  warn "no C compiler — llama-cpp-python may have used a prebuilt wheel; if not, install build-essential"
fi

step "probing GPU (informational)"
if command -v nvidia-smi >/dev/null 2>&1; then
  ok "nvidia-smi available"
else
  skip "no nvidia-smi (CPU-only inference is fine)"
fi

# ----- 4) directories + perms -----
step "ensuring local state dirs"
LOCAL_DATA="${REPO_ROOT}/data"
mkdir -p "${LOCAL_DATA}"/{keys,models,logs,tmpfs}
chmod 700 "${LOCAL_DATA}/keys"
ok "data/ tree ready"

step "checking tmpfs target"
if [[ -w /dev/shm ]]; then
  mkdir -p /dev/shm/secure-llm-dev
  ok "/dev/shm writable"
else
  warn "/dev/shm not writable; falling back to ${LOCAL_DATA}/tmpfs (dev only)"
fi

# ----- 5) dev config + identity -----
step "ensuring dev config"
CFG="${REPO_ROOT}/data/config.toml"
if [[ ! -f "${CFG}" ]]; then
  fix "writing default config.toml"
  cp "${REPO_ROOT}/server/secure_llm_server/_config.template.toml" "${CFG}" 2>/dev/null || {
    cat > "${CFG}" <<'EOF'
# Generated by bootstrap. Edit as needed; do not commit.
[server]
host = "127.0.0.1"
port = 8443
shutdown_grace_seconds = 10

[tls]
cert_file = "keys/dev-cert.pem"
key_file  = "keys/dev-key.pem"
min_version = "TLSv1.3"

[crypto]
key_dir = "keys"
authorized_clients = "keys/authorized_clients.toml"
session_ttl_seconds = 3600
session_max_lifetime_seconds = 28800
handshake_skew_seconds = 30

[models]
storage_dir = "models"
tmpfs_dir = "/dev/shm/secure-llm-dev"
max_loaded = 1
idle_timeout_seconds = 300
disk_quota_gb = 50
allow_download = true

[inference]
n_gpu_layers = 0
n_threads = 0
n_ctx_default = 2048
queue_depth_per_model = 8
max_tokens_hard_cap = 2048

[limits]
max_request_bytes = 8388608
max_response_stream_bytes = 67108864
rate_limit_rpm_per_client = 600
slowloris_header_timeout_seconds = 10

[observability]
log_level = "INFO"
log_format = "json"
metrics_enabled = true
metrics_bind = "127.0.0.1:9090"
log_dir = "logs"
ring_buffer_size = 10000
error_buffer_size = 1000
EOF
  }
else
  skip "config.toml exists"
fi

step "ensuring dev TLS certificate"
TLS_KEY="${REPO_ROOT}/data/keys/dev-key.pem"
TLS_CRT="${REPO_ROOT}/data/keys/dev-cert.pem"
if [[ ! -f "${TLS_KEY}" || ! -f "${TLS_CRT}" ]]; then
  fix "generating self-signed TLS cert"
  if command -v openssl >/dev/null 2>&1; then
    openssl req -x509 -newkey ed25519 -nodes \
      -keyout "${TLS_KEY}" -out "${TLS_CRT}" \
      -days 365 -subj "/CN=secure-llm-dev" >/dev/null 2>&1
    chmod 600 "${TLS_KEY}"
  else
    warn "openssl missing; TLS will fail until cert is provisioned"
  fi
else
  skip "TLS cert exists"
fi

step "ensuring server identity keys"
if [[ ! -f "${REPO_ROOT}/data/keys/server.x25519.key" ]]; then
  fix "generating server X25519 + Ed25519 identity"
  uv run python -m secure_llm_server.crypto.keystore init \
    --key-dir "${REPO_ROOT}/data/keys" || fail "keystore init failed"
else
  skip "server identity present"
fi

step "ensuring sample allowlist + known_hosts"
ALLOW="${REPO_ROOT}/data/keys/authorized_clients.toml"
if [[ ! -f "${ALLOW}" ]]; then
  fix "writing empty allowlist (add clients via 'sllm keygen' + edit)"
  cat > "${ALLOW}" <<'EOF'
# Each client = a TOML table under [[clients]].
# Required: x25519_pk, ed25519_pk (base64).  Optional: scopes, not_before, not_after, revoked.
# Example:
# [[clients]]
# name = "alice"
# x25519_pk = "..."
# ed25519_pk = "..."
# scopes = ["chat", "admin"]
EOF
fi

# ----- 6) doctor -----
step "running doctor"
if uv run python -m secure_llm_server.scripts_doctor; then
  ok "doctor passed"
else
  fail "doctor reported issues; fix above and re-run 'make bootstrap'"
fi

echo
printf "\033[1;32m[bootstrap done]\033[0m try 'make run' or 'make smoke'\n"
